# -*- coding: utf-8 -*-
"""python1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVfyfUPuTIIOIPTadITCc3-kqswAnESY
"""

print("hello ramu")

print("kle bk collage")

print(" mantu p sola")

print("mantu paragouda solabannavar")

print("Ramagouda")
print("Satigouda")
print("patil")

print("python")
print("is a")
print("powerful")
print("language")

print("python ",end = " ")
print("is a ",end = " ")
print("powerfull ",end = " ")
print("languages")

a = 10
b = 20

if a > b:
  print("hi")
else:
  print("hello")

name = "rama"
address = "bangalore"
pincode = 58848
collage = "chikodi  maddi"

print(name)
print(address)
print(pincode)
print(collage)

num=101
print(num)
print(type(num))

num=101.102
print(num)
print(type(num))

place="chikoddi"
print(place)
print(type(place))

a=5
b=10
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

a=100
b=400
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)
print(a==b)
print(a!=b)

print(99 != 2 or 5 == 5)

print(not(69 <= 70 and 10 <= 2))

print(34 == 43 and not(89 > 31 or 7!=1))

a=10
print(a)
a+=10
print(a)
a-=10
print(a)
a*=10
print(a)
a/=10
print(a)
a%=10
print(a)
a//=10
print(a)
a**=10
print(a)

a=10
b=20
print("before swapping",a,b)
a=b+a
b=a-b
a=a-b
print("after swapping",a,b)

if 10==10:
  print("10 is Equal to 10")

A=10
if a%2== 0:

  print("number is positive")
else:
    print("number is negative")

per=int(input("enter your percentage \n"))
if per>=90:
  print("Grade A")
elif per>=80:
  print("Grade B")

elif per>=70:
  print("Grade C")
else:
  print("you are fail")

colour =input("Enter signal colour :")
if colour=="Red":
  print("stop the vehicles")
elif colour=="yellow":
  print("ready to move")
elif colour=="Green":
  print("go")
else:
  print("Invaliad colour🚴‍♀️")

print("diarymilk  choklat")

num=5
fact=1
while num>0:
     fact*=num
     num-=1
print(fact)

num=4
i=1
while i <=10:
  print(num,"*",i,"=",num*i)
  i=i+1

num=7
count=0
for i in range(1,num+1):
  if num%i==0:
    count+=1
if count==2:
  print("prime number")
else:
  print("not prime number")

def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b

fibonacci(10)

number_to_check = 153

current_sum = 0
remainder = 0
temp_num = number_to_check
while temp_num > 0:
    remainder = temp_num % 10
    current_sum = current_sum + remainder * remainder * remainder
    temp_num = temp_num // 10
if number_to_check == current_sum:
  print("armstrong number")
else:
  print("not armstrong number")

for i in range (1,7):
   for j in range (2,7):
    print("*",end=" ")
print()

numbers=[1,2,3,4,5,6,7,]
for num in numbers:
  print(num)

def fun():
   print("hello function")
fun()
fun()

def Example():
   return "hello function"
print(Example())

class car:
  Brand="Depander"
  price=250
  year=2000
  colour="Red"

depander=car()
print(car.Brand)
print(car.price)
print(car.year)
print(car.colour)

class student:
  name="Ajit"
  USN="U15DO25S0026"
  Age=19
  place="bangalore"
  course="BCA"
  dob=12/6/2006
  sem= "second"
  div="A"
  gender="male"
  bloodgroup="o+ve"
Ajit=student()
print(Ajit.name)

class College:
    Total_seat = 50
    Department = "BCA"
    Duration = "3 year"
    fees = 60000

    def study(self):
        print(f"We are studying {self.Department} department")

    def Exam(self):
        print("I have completed first sem exam")

    def function(self):
        print("I paid {self.fees} for college fest function")
student = College()
student.study()
print("A section total_students are:", student.Total_seat)
student.function()
print(student.Duration)
student.Exam()
print(student.Department)

class Vehicle:
    def __init__(self, brand, price):
        self.brand = brand
        self.price = price

car = Vehicle("Toyota", 25000)
print(car.brand)
print(car.price)
print("=======")

class Bank:
    def __init__(self, balance):
        self._balance = balance

    def deposit(self, amount):
        self._balance += amount

    def withdrawn(self, amount):
        self._balance -= amount

    def get_balance(self):
        return self._balance


obj = Bank(1000)
print(obj.get_balance())

obj.withdrawn(200)
print("current balance is :", obj.get_balance())

class Bank:
      def __init__(self,balance):
        self._balance = balance
      def Deposit(self,amount):
          if amount > 0:
             self._balance +=amount
             print("amount deposit to bank,amount is")
          else:
            print("check amount")

class Father:
   Age =45
   Name = "Shiva"

   def work(self):
       print("my father is working im  my village")

class Mother:
   colour ="black"
   place ="kabbura"

   def work(self):
       print("my mom is a Teacher")

class child (Father,Mother):
    study ="BCA"
    address ="Kabbura"

    def course(self):
        print("I'm studying BCA in National college")

obj = child()
obj.work()
print(obj.study)
obj.course()
obj.work()
print("my father age is",obj.Age)

class Grand_parents :
    def Mothod1(self):
      print("🏍️🏍️🏍️🏍️🏍️🏍️🏍️🏍️🏍️")

class parents(Grand_parents):
    def Mothod2(self):
      print("🚗🚗🚗🚗🚗🚗🚗🚗🚗")

class childrens(parents):
     def Method3(self):
       print("🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️🚴‍♀️")

obj = childrens()
obj.Mothod1()
obj.Mothod2()
obj.Method3()

class A (A):
  def fun1(self):
    print("**********")
class B(A):
  def fun2(self):
    print("$$$$$$$$$$")
class C(A):
  def fun3(self):
    print("!!!!!!!!!!")

obj1 =B()
obj2 =C()
obj1.fun2()
obj1.fun1()
obj2

class A:
  def M1(self):
    print("AAAAAAAAAA")
class B(A):
  def M2(self):
      print("BBBBBBBBBB")
class C(A):
  def M3(self):
    print("CCCCCCCCCC")
class D (B,C):
  def M4(self):
    print("DDDDDDDDDD")

first = D()
first.M1()
first.M2()
first.M3()
first.M4()

class A:
  def add(self,a,b,c=5):
    print(a+b+c)

obj = A()
obj.add(4,6)
obj.add(10,10,10)
obj.add(b=30,c=20,a=40)
obj.add(0,10)

class Animal:
  def sound(self):
    print("Animal make sound")

class Dog(Animal):
  def sound(self):
    print("Dog make sound like is Meow🐕🐕🐕🐕🐕🐕")

class cat (Animal):
  def sound(self):
    print("cat make sound Like is Meow🐈🐈🐈🐈🐈🐈")

class Snake (Animal):
  def sound(self):
    print("🐍🐍🐍🐍🐍🐍")

class cow (Animal):
  def sound(self):
    print("🐄🐄🐄🐄🐄🐄")

obj1= Dog()
obj2= cat()
obj3= Snake()
obj4= cow()

obj1.sound()
obj2.sound()
# obj.sound() # Removed the incorrect call to LinearRegression obj
obj3.sound()
obj4.sound()

def sound(animal_instance):
  animal_instance.sound()
A = Animal() # Corrected: animal() -> Animal()
sound(A)
B = Dog()
sound(B)
C = cat()
sound(C)
D = cow() # Corrected: cow -> cow()
sound(D)

class Animal:
    def sound(self):
        print("Animal makes a sound")

class Dog(Animal):
    def sound(self):
        print("Dog barks 🐕🐕🐕")

class Cat(Animal):
    def sound(self):
        print("Cat meows 🐈🐈🐈")

class Snake(Animal):
    def sound(self):
        print("Snake hisses 🐍🐍🐍")

class Cow(Animal):
    def sound(self):
        print("Cow moos 🐄🐄🐄")



obj1 = Dog()
obj2 = Cat()
obj3 = Snake()
obj4 = Cow()


obj1.sound()
obj2.sound()
obj3.sound()
obj4.sound()

print("---- Polymorphism ----")


def make_sound(animal):
    animal.sound()

A = Animal()
B = Dog()
C = Cat()
D = Cow()

make_sound(A)
make_sound(B)
make_sound(C)
make_sound(D)

class vehicle(ABC):
  def cost(self):
      print("Total cost is 5lakh")

  def speed (self):t

class car (vehicle):
  def speed(self):
    print("car is going 60km per hour")
  def company(self):

marks=[10,20,30,40,50]
print(marks)00000

Details =[101,"Basavaraj",8.53,"true",12]
print(Details[-1:-4:-2])

csv_data ="""name,marks,attendance
Ravi,78,85
Anu,65,70
Raj,90,95
"""
with open ("student.csv","w")as f:
      f.write(csv_data)

print("student.csv created successfully")

import csv

with open("student.csv","r")as file:
  reader =csv.reader(file)
  for row in reader:
    print(row)

marks=[50,70,60,80,90]
print(marks)
print(type(marks))
print(len(marks))
marks.append(60)
print(marks)
marks.append(70)
print(marks)
print(marks.remove(70))
print(marks)
print(marks.count(60))
print(marks.pop())
marks.insert(0,20)
print(marks)
marks.sort()
print(marks)
print(marks[4])

marks = (99,60,70,45,55,78,95)
print(marks)
print(type(marks))
print(len(marks))
print(marks.count(67))
print(marks.index(78))
print(marks[1:5])

num1 ={1,2,3,4,5}
num2 ={2,3,4,6,8,9}

print(num1.union(num2))
print(num1&num2)
print(num1|num2)
print(num1.intersection(num2))
print(num1^num2)
print(num1.difference(num2))
print(num2.difference(num1))

Example ={
  "USN Number" : 111,
   "name"      : "Mantu",
   "Gender"    : "Male",
   "Address"   : "Chikodi"

   }
print(Example)
print(len(Example))
print(type(Example))
Example["pincode"]=25842
print(Example)
Example["Age"]=26
print(Example)
print(Example["name"])
Example["Address"] = "bangalore"
print(Example)
print(Example.get("Age"))
print(Example.pop("Gender"))
print(Example.popitem())
print(Example)
print(Example.keys())
print(Example.values())
print(Example.items())
print(Example.update({"College" : "city collage chikodi"}))
print(Example)
del Example["pincode"]
print(Example)
Example.clear()
print(Example)

import math
print(math.pow(1,2))
print(math.sqrt(10))
print(math.factorial(2))
print(math.pi)
print(math.ceil)

import random
print(random.randint(1,10))
print(random.random())
print(random.choice(["pen","paper","mobile"]))

import calendar
print(calendar.month(2025,10))
print(calendar)

import calendar
year = 2026
for month in range (1,12+1):
  print(calendar.month(year,month),end = " ")

file =open("result.txt","w")
file.write("Ravi - Pass\nAnu - Pass\nRaj - Pass")
file.close()
print("result.txt created succesfully")

file =open("result.txt", "r")
content = file.read()
print(content)
file.close()

csv_data ="""name,marks,attendance
Ravi,78,85
Anu,65,70
Raj,90,95

"""
with open ("student.csv","w")as f:
      f.write(csv_data)

print("student.csv created successfully")

import csv

with open("student.csv","r")as file:
  reader =csv.reader(file)
  for row in reader:
    print(row)

import  pandas as pd
data =pd.read_csv("student.csv")
print(data)
print(type(data))
print(data[["name","attendance"]])

data =pd.DataFrame({
    "name":["Ravi","Anu","Raj"],
    "marks":[78,None,90]
    })
print(data)
data["marks"]

import numpy as np
import pandas as pd

marks = np.array([78, 65, 90,55])
data= pd.DataFrame(marks,columns=["marks"])
print(data)

import pandas as pd

data = pd.read_csv("student.csv")
avg = data["marks"].mean()

print("average marks:",avg)

print("above averag students:")
print(data[data["marks"]>avg])

csv_data ="""name,marks,attendance
Ravi,78,85
Anu,65,70
Raj,90,95

"""
with open ("student.csv","w")as f:
      f.write(csv_data)

print("student.csv created successfully")

import pandas as pd
data = pd.DataFrame({
    "name":["Ravi","Anu","Raj","Ravi"],
    "marks":[78,65,90,78]
})
print(data)
print(data.duplicated())

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression # Import LogisticRegression

# step 1: create dataet
data = pd.DataFrame({ # Corrected typo: dataFramme -> DataFrame
    "marks": [78, 65, 40, 90, 55, 88, 30, 72],
    "attendance" : [85, 70, 60, 95, 50, 80, 45, 75], # Added missing attendance value to match marks
    "result" : [1, 1,0,1,0,1,0,1]
    })
#step2: separate X and y
X = data[["marks","attendance"]]
y = data["result"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#step 4: Train model
model = LogisticRegression()
model.fit(X_train,y_train)

#step 5: Test model
accuracy =model.score(X_test,y_test)
print("Accuracy:",accuracy)

#------------------PLOT-----------------

# SEPARATE PASS AND FAIL STUDENT
pass_data = data[data["result"]==1]
fail_data = data[data["result"]==0]

plt.figure(figsize=(8,6))

# scatter plot
plt.scatter(pass_data["marks"],pass_data["attendance"],label="Pass") # Corrected pass_student to pass_data
plt.scatter(fail_data["marks"],fail_data["attendance"],label="fail") # Corrected fail_student to fail_data

# Labels and title
plt.xlabel("Marks") # Corrected typo: xlable -> xlabel
plt.ylabel("Attendance") # Corrected typo: ylable -> ylabel
plt.title("Student Performance: Marks vs Attendance") # Added title
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd

data = pd.DataFrame({
    "name"

import pandas as pd
data = pd.DataFrame({
    "gender" :["male","Female","Female","male"],
    "marks" :[78,65,90,55]
})
print(data)
print(type(data))
data["gender"] =data["gender"].map({"male":0,"Female":1})
print(data)

csv_data ="""name,marks,attendance,result
Ravi,78,85,pass
Anu,65,70,pass
Raj,35,40,fail
Rama,90,95,pass
Mantu,50,55,pass

"""
with open ("result.csv","w")as f:
      f.write(csv_data)

print("result.csv created successfully")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt # Import matplotlib

data = pd.DataFrame({
    "marks": [78, 65, 35, 90, 50],
    "attendence": [85, 70, 40, 95, 55],
    "result": ["pass", "pass", "fail", "pass", "pass"]
})

print("-------------")

data["result"] = data["result"].map({"pass": 1, "fail": 0})
print(data)

print("-------------")
print(data.describe())

print("=============")

x = data[["marks", "attendence"]]
y = data["result"]

print(x)
print("=============")
print(y)

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

print("=============")
print(x_train)

print("=============")
print(x_test)

print("=============")
print(y_train)

print("=============")
print(y_test)

model = LogisticRegression()
model.fit(x_train, y_train)

print("=============")
print(model.predict(x_test))

print("=============")
accuracy=model.score(x_test, y_test)

print("=============")
print(accuracy)
new_result =[[60, 65]]
prediction = model.predict(new_result)

print("Prediction is " + ("pass" if prediction[0]==1 else "fail")) # Fixed SyntaxError

pass_data = data[data["result"]==1]
fail_data = data[data["result"]==0]


plt.figure(figsize=(8,6))

plt.scatter(pass_data["marks"],pass_data["attendence"],label="Pass") # Fixed variable name and column name
plt.scatter(fail_data["marks"],fail_data["attendence"],label="fail") # Fixed variable name and column name
plt.xlabel("marks of BCA") # Fixed typo
plt.ylabel("attendence") # Fixed typo
plt.title("Student Result Prediction") # Added a title
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data = pd.DataFrame({
    "marks": [78, 65, 35, 90, 50],
    "attendence": [85, 70, 40, 95, 55],
    "result": ["pass", "pass", "fail", "pass", "pass"]
})

print("-------------")

data["result"] = data["result"].map({"pass": 1, "fail": 0})
print(data)

print("-------------")
print(data.describe())

print("=============")

x = data[["marks", "attendence"]]
y = data["result"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = LogisticRegression()
model.fit(x_train, y_train)

print("=============")
print("Predicted:", model.predict(x_test))

accuracy = model.score(x_test, y_test)
print("Accuracy:", accuracy)

# New prediction
new_result = pd.DataFrame([[60, 65]], columns=["marks", "attendence"])
prediction = model.predict(new_result)

print("Prediction is", "pass" if prediction[0] == 1 else "fail")

# Separate pass & fail students
pass_data = data[data["result"] == 1]
fail_data = data[data["result"] == 0]

# Plot
plt.figure(figsize=(8, 6))
plt.scatter(pass_data["marks"], pass_data["attendence"], label="Pass", color="green")
plt.scatter(fail_data["marks"], fail_data["attendence"], label="Fail", color="red")

plt.xlabel("Marks of BCA")
plt.ylabel("Attendance")
plt.title("Student Result Prediction")
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data =pd.DataFrame({
    "name":["Ravi","Anu","Raj","sita","Amita"],
    "marks":[78,65,90,55,88],
    "Attendence":[85,70,95,60,92]
})
print(data)
print(data.shape)
print(data.columns)
print(data.head)
print(data.describe())
print(data["marks"].mean())
print(data["marks"].max())
print(data["marks"].min())
print(data["Attendence"].mean())
print(data["Attendence"].max())
print(data["Attendence"].min())
weak_student =data[data["marks"]<60]
print(weak_student)
top_student =data[data["marks"]>85]
print(top_student)

print(data[["marks","Attendence"]].corr())

plt.scatter(data["Attendence"],data["marks"])
plt.xlabel("Attendence")
plt.ylabel("marks")
plt.title("Attendence vs marks")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
row =np.array(["A","B","C","D","E","F"])
column =np.array([4,8,2,7,9,11])
plt.bar(row,column,color ="green",edgecolor ="gold")
plt.show

import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data = pd.DataFrame({
    "Ice_creame" : [10,20,40,25,45,50,60],
    "price" : [40,60,100,120,150,175,190]
})
print(data)

x = data[["Ice_creame"]]
y = data["price"]

x_train, x_test, y_train, y_test = train_test_split(  x, y, test_size=0.25)

obj = LinearRegression()
obj.fit(x_train, y_train)
print("prediction is:",obj.predict(x_test))
print(y_test.values)

plt.scatter(x,y)
plt.plot(x,obj.predict(x))
plt.show()

import matplotlib.pyplot as plt
import numpy as np

Things =np.array(["pen","Book","Mobile","Bottle","chair","Bag","Cable","Laptop"])
price =np.array([10,40,2000,30,150,300,200,5000])
plt.bar(Things,price,color ="skyblue",edgecolor ="black")
plt.show()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

marks =[20,40,30,50,70,60,90,80]
plt.hist(marks,bins=5,edgecolor ="black")
plt.show()

import matplotlib.pyplot as plt

Hours =[8.0,8.30,9.0,9.30,10.0,11.0,12.0,1.0]
temp = ["20C","25C","28C","30C","25C","33C","35C","23C"]
plt.plot(Hours,temp)
plt.grid()
plt.show()

import matplotlib.pyplot as plt
subject  =["C programming","DBMS","Maths","Accounting","Kannada","English"]
marks =[72,55,60,78,75,45]
plt.pie(marks,labels =subject,autopct ='%1.1f%%')
plt.show()

import matplotlib.pyplot as plt

Hours =[2,3,4,5,6,7,8,9]
marks =[40,50,60,68,74,80,90,97]
plt.scatter(Hours,marks,color ="green")
plt.show()

import matplotlib.pyplot as plt

salary =[20000,25000,30000,35000,40000]
plt.boxplot(salary)
plt.title("salary distribuction")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data =np.array([
    [10,20,30],
    [30,20,40],
    [40,50,60]
])
plt.imshow(data)
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt

year =[2020,2021,2022,2023,2024,2025]
Population =[100000,150000,180000,200000,280000,300000]
plt.fill_between(year,Population,color ="skyblue",edgecolor ="black")
plt.show()

import matplotlib.pyplot as plt

overs =[1,2,3,4,5,6]
score =[10,13,20,18,22,32]
size =[300,500,750,250,800,200]

plt.scatter(overs,score,s=size,color ="black")
plt.show()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.DataFrame({
    "Experiences": [1, 4, 5, 3, 4, 6],
    "salary": [10000, 30000, 50000, 40000, 30000, 60000]
})

print(data)

x = data[["Experiences"]]
y = data["salary"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

Example= LinearRegression()

Example.fit(x_train, y_train)



print("Predictions:", predictions)
print("Actual:", y_test.values)

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Area, Rooms, Rent
x = np.array([
    [1000, 4, 10000],
    [1500, 5, 12000],
    [1200, 5, 11000],
    [2000, 6, 20000],
    [1700, 6, 17000]
])
y = np.array([8, 15, 10, 20, 17])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

print("Prediction values are:", model.predict(x_test))

new_values = [[2500, 8, 25000]]
print("Prediction of new land value is:", model.predict(new_values))

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import math

data =pd.DataFrame({
    "Quantity" :[1,2,3,4,5,6,7,8],
    "price" :[100,200,300,400,500,600,700,800]
})
print(data)

x =data[["Quantity"]]
y =data["price"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

obj =LinearRegression()

obj.fit(x_train,y_train)

prediction =obj.predict(x_test)
print("prediction values is:",prediction)

MAE =mean_absolute_error(y_test,prediction)
print("mean absolute error is:",mean_absolute_error(y_test,prediction))
print(MAE)

MSE=mean_squared_error(y_test,prediction)
print("mean squared error is:",mean_squared_error(y_test,prediction))

RMSE =math.sqrt(MSE)
print("Root mean squared error is:",RMSE)

R2 =r2_score(y_test,prediction)
print("r2 score is:",R2)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data =pd.DataFrame({
    "message_words" :[10,8,15,13,45,5,50,12],
    "length" :[50,30,60,25,70,20,80,35],
    "result" :[0,1,0,1,0,1,0,1]
})
print(data)

x =data[["message_words","length"]]
y =data["result"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

obj =LogisticRegression()

obj.fit(x_train,y_train)
print("prediction  values is:",obj.predict(x_test))

accuracy =obj.score(x_test,y_test)
print("accuracy is:",accuracy)

new_values =[[20,45]]
print("prediction of new values is:",obj.predict(new_values))

if prediction[0]==1:
    print("spam")
else:
    print("not spam")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

x = np.array([
    [2,60],
    [4,65],
    [6,70],
    [8,80],
    [10,90],
    [1,50],
    [3,55],
    [7,75]
])

y = np.array([0,0,1,1,1,0,0,1]) # Corrected: Added one more element to match the length of x

x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2)

obj = LinearRegression()

obj.fit(x_train,y_train)

prediction =obj.predict([[5,67]])
print("prediction of new values is:",prediction)

pre =obj.predict(x_test)

accuracy =accuracy_score(y_test,np.round(pre)) # Rounding predictions for classification metrics
print("accuracy values is:",accuracy)

precision =precision_score(y_test,np.round(pre)) # Rounding predictions
print("precision values is:",precision)

recall =recall_score(y_test,np.round(pre)) # Rounding predictions
print("recall values is:",recall)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

x = np.array([
    [2,60],
    [4,65],
    [6,70],
    [8,80],
    [10,90],
    [1,50],
    [3,55],
    [7,75]
])

y = np.array([0,0,1,1,1,0,0,1])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(x_train, y_train)

prediction = model.predict([[5,67]])
print("Prediction of new values is:", prediction)

pre = model.predict(x_test)

accuracy = accuracy_score(y_test, pre)
print("Accuracy value is:", accuracy)

precision = precision_score(y_test, pre)
print("Accuracy value is:", accuracy)

recall = recall_score(y_test, pre)
print("Recall value is:", recall)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

x=np.array([
    [2,60],
    [4,65],
    [6,70],
    [8,80],
    [10,90],
    [1,50],
    [3,55],
    [7,75]
])
# output variable 0:pas 1:fail
y =np.array([0,0,1,1,1,0,0,1])
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2)

knn =KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train,y_train)

prediction =knn.predict([[5,67]])
print("prediction of new values is:",prediction)

print("Accuracy score is :",knn.score(x_test,y_test))

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression # Changed to LinearRegression
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt # Added import for matplotlib

np.random.seed(0)
x = 2 * np.random.rand(20, 1)
Y = 3 * x**2 + 1 + np.random.rand(20, 1) * 0.5

x_train = x
y_train = Y

poly = PolynomialFeatures(degree=8)
x_poly = poly.fit_transf
orm(x_train)

overfit_model = LinearRegression()
overfit_model.fit(x_poly, y_train)

x_range =np.linspace(0,2,200).reshape(-1,1)
x_range_poly =poly.transform(x_range)

y_overfit_poly =overfit_model.predict(x_range_poly)

plt.scatter(x,Y,label ="Data")
plt.plot(x_range,y_overfit_poly,label ="overfit model",color ="red")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score

x_actual =[1,0,1,0,0,1,1,0,1,1]
y_pred =[0,1,1,0,1,0,1,0,1,1]

cm = confusion_matrix(x_actual,y-pred)

print("Accuracy score values is:",accuracy_score(x_actual,y_pred))

print("precision score values is:",precision_score(x_actual,y_pred))

print("recall score values is:",recall_score(x_actual,y_pred))

print("F1 score values is:",f1_score(x_actual,y_pred))

plt.fogure(size =(5,5))
plt.imshow(cm)
plt.

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data = pd.DataFrame({
    "overs":[5,6,7,8,9,10],
    "Runs":[5,10,15,20,25,30]
})
print(data)

x = data[["overs"]]
y = data["Runs"]

x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.25)

BCA =LinearRegression()
BCA.fit(x_train,y_train)

pred =BCA.predict(x_test)
print("prediction of x_test values is:",BCA.predict(x_test))

print("prediction of new value is :",BCA.predict([[15]]))

rows =np.linspace(5,30,100).reshape(-1,1)

column =BCA.predict(rows)

plt.scatter(x,y)
plt.plot(rows,column,color ="red")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

x =np.array([
    [1,2],
    [1,4],
    [1,0],
    [10,2],
    [10,4],
    [10,0]
])

kmeans_model = KMeans(n_clusters=2, random_state=0)
kmeans_model.fit(x)

labels =kmeans_model.labels_
centroids =kmeans_model.cluster_centers_

print("cluster labels:",labels)
print("centroids:",centroids)

plt.scatter(x[:,0],x[:,1])
plt.scatter(centroids[:,0],centroids[:,1],marker ='x',s =200)
plt.xlabel("feature 1")
plt.ylabel("feature 2")
plt.title("unsupervised learning-kmeans clustering")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

iris =datasets.load_iris()

x =iris.data[:,:2]
Y =iris.target

print(iris)

X_train,x_test,Y_train,y_test =train_test_split(x,Y,test_size =0.3,random_state =42)

model =SVC(kernel ='linear')
model.fit(X_train,Y_train)

y_pred =model.predict(x_test)

print("Accuracy :",accuracy_score(y_test,y_pred))

x_min,x_max =x[:,0].min()-1,x[:,0].max()+1
y_min,y_max =x[:,0].min()-1,x[:,0].max()+1

xx,yy =np.meshgrid(
    np.linspace(x_min,x_max,200),
    np.linspace(y_min,y_max,200)
)

z =model.predict(np.c_[xx.ravel(),yy.ravel()])
z =z.reshape(xx.shape)

plt.contourf(xx,yy,z,alpha =0.3)

plt.scatter(x[:,0],x[:,1],c=Y)

plt.xlabel("sepal Length")
plt.ylabel("sepal Width")
plt.title("SVM Decision Boundary")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data =pd.DataFrame({
    "s_hours" :[1,2,3,4,5,6,7,8],
    "marks" :[30,35,40,45,50,55,60,65]
})
print(data)

sns.scatterplot(x="s_hours",y="marks",data =data)
plt.xlabel("study hours")
plt.ylabel("marks")
plt.title("study hours vs marks")
plt.grid(True)
plt.show()

from sklearn.model_selection import  cross_val_score
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data =pd.DataFrame({
     "Age" :[25,45,35,50,23,40,60,48,33,55],
     "BP" :[120,140,130,150,110,135,160,145,160,155],
     "Disease" :[0,1,0,1,0,1,1,1,0,1]
})

x =data[["Age","BP"]]
y =data["Disease"]

obj =RandomForestClassifier(n_estimators=100)
score =cross_val_score(obj,x,y,cv=5)
print("cross value validation score is :",score)
print("Average of score value is :",score.mean())

from sklearn.preprocessing import StandardScaler
import pandas as pd

data =pd.DataFrame({
    "Experince" :[1,2,3,4,5],
    "Age" :[22,25,30,35,40]
})
print("Actual data 's",data)

obj =StandardScaler()
Data =obj.fit_transform(data)

print("scaled Data's",Data)

from sklearn.ensemble import RandomForestClassifier
import pandas as pd

data =pd.DataFrame({
    "Income" :[30000,40000,50000,60000,70000],
    "credit_score" :[600,500,700,750 ,800],
    "loan_Approved ":[0,0,1,1,1]
})
print(data)
print(data.shape)
print(data[data["credit_score"]>700])

x = data[["Income","credit_score"]]
y = data["loan_Approved "]

obj =RandomForestClassifier(n_estimators=50,random_state =42)

obj.fit(x,y)

print("prediction of autual values is :",obj.predict(x))

new_values =[[50000,100]]
print("new values prediction is:",obj.predict(new_values))

print("Loan is Approved")

#step-1
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

#step -2
data = pd.DataFrame({
    "Experience" : np.random.randint(1,15,250),
    "EducationalLevel" :np.random.randint(1,5,250),
    "ProjectsHandled" :np.random.randint(1,20,250),
    "WorkingHours" :np.random.randint(1,12,250),
    "PerformanceScore" :np.random.randint(1,6,250),

    })

#step - 3
data["Salary"] = (
    data["Experience"] * 5000 +
    data["EducationalLevel"] * 8000 +
    data["ProjectsHandled"] * 1500 +
    data["PerformanceScore"] * 4000 +
    np.random.randint(-10000,10000,250)
)

#Attrition formula
data["Attrition"] = np.where(
    (data["WorkingHours"] > 10) &
    (data["PerformanceScore"] < 3) ,1 ,0

)

print("Dataset Preview:\n",data.head())

#step -3
#plot 1:Exp vs Sal
plt.figure()
plt.scatter(data["Experience"],data["Salary"])
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.title("Experience vs Salary")
plt.show()

#plot 2: Attrition count
plt.figure()
data["Attrition"].value_counts().plot(kind="bar")
plt.title("Attrition Distribution")
plt.show()

#plot 3 :correlation Heatmap
plt.figure()
sns.heatmap(data.corr(),annot=True,cmap="coolwarm")
plt.title(" Feature Correlation")
plt.show()

#step - 4
x_reg = data.drop(["Salary","Attrition"], axis=1)
y_reg = data["Salary"]

x_train_r,x_test_r,y_train_r,y_test_r = train_test_split(x_reg, y_reg, test_size=0.3, random_state=42)

scaler = StandardScaler()
x_train_r = scaler.fit_transform(x_train_r)
x_test_r = scaler.transform(x_test_r)

reg_model = LinearRegression()
reg_model.fit(x_train_r,y_train_r)

y_pred_r = reg_model.predict(x_test_r)

print("\nSalary Prediction result")
print("R2 Score:", r2_score(y_test_r, y_pred_r))
print("RMSE:", np.sqrt(mean_squared_error(y_test_r, y_pred_r)))

#plot -4 : Actual VS Predicated Salary
plt.figure()
plt.scatter(y_test_r,y_pred_r)
plt.xlabel("Actual Salary")
plt.ylabel("Predicted Salary")
plt.title("Actual vs Predicted Salary")
plt.show()

 #step - 5:
x_clf = data.drop(["Salary","Attrition"], axis=1)
y_clf = data["Attrition"]

x_train_c,x_test_c,y_train_c,y_test_c = train_test_split(x_clf, y_clf, test_size=0.3, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100,random_state=42)
rf_model.fit(x_train_c,y_train_c)

y_pred_c = rf_model.predict(x_test_c)

print("\nAttrition Prediction result")
print("Accuracy :", accuracy_score(y_test_c, y_pred_c))
print("confusion matrix:\n",confusion_matrix(y_test_c, y_pred_c))

#cross validation
cv_scores = cross_val_score(rf_model, x_clf, y_clf, cv=5)
print("Cross Validation Accuracy:", cv_scores.mean())

#plot - 5 : Feature Importance
importance = rf_model.feature_importances_
feature_names = x_clf.columns

plt.figure()
plt.bar(feature_names, importance)
plt.xticks(rotation=45)
plt.title("Feature Importance - Attriton Model")
plt.show()

print("\nProject Completed Successfully!")